# -----------------------
# Authentication
# -----------------------

@authUrl = login.microsoftonline.com/{{TENANT_ID}}
@tsiApi = https%3A%2F%2Fapi.timeseries.azure.com%2F

###
# @name tsiLogin
POST https://{{authUrl}}/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{CLIENT_ID}}&client_secret={{CLIENT_SECRET}}&resource={{tsiApi}}

###
@tsiToken = {{tsiLogin.response.body.access_token}}


# -----------------------
# Environments
# -----------------------

###
# @name environments
GET https://api.timeseries.azure.com/environments?api-version=2016-12-12
Authorization: Bearer {{tsiToken}}
Content-Type: application/json

###
@myEnv = {{environments.response.body.environments[1].environmentId}}



# -----------------------
# Events
# -----------------------
@from = 2019-10-21T18:38:00Z
@to = 2019-10-21T18:38:40Z

POST https://{{myEnv}}.env.timeseries.azure.com/timeseries/query?api-version=2018-11-01-preview
Authorization: Bearer {{tsiToken}}
Content-Type: application/json

{
  "getEvents": {
    "timeSeriesId": [
      "Sensor_57"
    ],
    "searchSpan": {
        "from":  "{{from}}",
        "to":  "{{to}}"
    }
  }
}


POST https://{{myEnv}}.env.timeseries.azure.com/timeseries/query?api-version=2018-11-01-preview
Authorization: Bearer {{tsiToken}}
Content-Type: application/json

{
  "getEvents": {
    "timeSeriesId": [
      "Sensor_57"
    ],
    "searchSpan": {
        "from":  "{{from}}",
        "to":  "{{to}}"
    },
    "filter": { "tsx": "($event.Value.Double != null) AND ($event.Value.Double > 30.0)" },
    "projectedProperties": [
      {"name":"Id","type":"String"},
      {"name":"Value","type":"Double"},
      {"name":"Units","type":"String"}
    ]
  }
}

###
POST https://{{myEnv}}.env.timeseries.azure.com/timeseries/query?api-version=2018-11-01-preview
Authorization: Bearer {{tsiToken}}
Content-Type: application/json

{
  "getEvents": {
    "timeSeriesName" : "Atmospheric Pressure (Bristol-WM1)",
    "searchSpan": {
      "from":  "{{from}}",
      "to":  "{{to}}"
    }
  }
}


###
POST https://{{myEnv}}.env.timeseries.azure.com/timeseries/query?api-version=2018-11-01-preview
Authorization: Bearer {{tsiToken}}
Content-Type: application/json

{
  "getSeries": {
    "timeSeriesName" : "Atmospheric Pressure (Bristol-WM1)",
    "searchSpan": {
        "from":  "{{from}}",
        "to":  "{{to}}"
    },
    "projectedVariables": ["Atmospheric Pressure"]
  }
}

###
POST https://{{myEnv}}.env.timeseries.azure.com/timeseries/query?api-version=2018-11-01-preview
Authorization: Bearer {{tsiToken}}
Content-Type: application/json

{
  "getSeries": {
    "timeSeriesName" : "Bearing Temperature (Franklin-WM3)",
    "searchSpan": {
        "from":  "{{from}}",
        "to":  "{{to}}"
    },
    "projectedVariables": ["Bearing Temperature"]
  }
}

###
POST https://{{myEnv}}.env.timeseries.azure.com/timeseries/query?api-version=2018-11-01-preview
Authorization: Bearer {{tsiToken}}
Content-Type: application/json

{
  "getEvents": {
    "timeSeriesId": [
      "Sensor_87",
      "Sensor_57"
    ],
    "searchSpan": {
        "from":  "{{from}}",
        "to":  "{{to}}"
    }
  }
}
